name = "TetraGray"
version = "0.1.0"
defaultTargets = ["tetragray"]
# for lean copilot
# moreLinkArgs = [
#     "-L./.lake/packages/LeanCopilot/.lake/build/lib",
#     "-lctranslate2"
# ]

[[require]]
name = "aesop"
# scope = "leanprover-community"
git = "https://github.com/leanprover-community/aesop.git"
rev = "master"


# TODO: put in PR to update to Lean 4.13
# [[require]]
# name = "interval"
# # scope = "girving"
# git = "https://github.com/girving/interval.git"
# rev = "main"


[[lean_lib]]
name = "TetraGray"

[[lean_exe]]
name = "tetragray"
root = "Main"

# [[require]]
# name = "llm.lean"
# git = "https://github.com/alok/llm.lean"
# rev = "main"
[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "LSpec"
git = "https://github.com/argumentcomputer/LSpec"
rev = "main"
