name = "TetraGray"
version = "0.1.0"
defaultTargets = ["tetragray"]

[[lean_lib]]
name = "TetraGray"

[[lean_exe]]
name = "tetragray"
root = "Main"

# [[require]]
# name = "llm.lean"
# git = "https://github.com/alok/llm.lean"
# rev = "main"

# [[require]]
# name = "scilean"
# git = "https://github.com/lecopivo/scilean"
# rev = "master"

# [[require]]
# name = "interval"
# git = "https://github.com/girving/interval.git"
# rev = "main"

# [[require]]
# name = "mathlib"
# git = "https://github.com/leanprover-community/mathlib4.git"
# rev = "master"

# [[require]]
# name = "NodeGraph"
# git = "https://github.com/adamtopaz/NodeGraph.git"
# rev = "master"

# [[require]]
# name = "batteries"
# scope = "leanprover-community"
# rev = "main"

